unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse
set -g status-right ""
set -g base-index 1
# set session base index to 1 as well (https://unix.stackexchange.com/questions/313577/how-to-make-tmux-sessions-count-from-1-instead-of-0)
bind-key s choose-tree -ZsK '#{e|+:1,#{line}}'

set-option -g status-interval 5
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b;=6:pane_current_path}'

bind h split-window -hc "#{pane_current_path}"
bind v split-window -vc "#{pane_current_path}"
bind b new-window -c "#{pane_current_path}"
bind-key x kill-pane

bind-key t new-window -c "#{pane_current_path}" 'micro $(fzf --preview="bat -f {}")'

# close session but open the next one if it exists
bind-key X run-shell ~/.config/tmux/close-and-open-next.sh

# move between words in copy-mode
bind-key -T copy-mode C-Right send-keys -X next-word-end
bind-key -T copy-mode C-Left send-keys -X previous-word

# start copy-mode  Shift+Up
bind-key S-Up copy-mode

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sidebar'

set -g @plugin 'tmux-plugins/tmux-open'
set -g @open-S 'https://www.duckduckgo.com/?q='

set -g @plugin 'chris-paganon/tmux-cdls'
set -g @cdls-toggle "d"

run '/usr/share/tmux-plugin-manager/tpm'
